resources:
  - name: git_source
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: GITHUB_MPATEL
      # Repository path, including org name/repo name
      path: MaharshiPatel/requestToUsage
      buildOn:
        pullRequestCreate: true
        commit: true
      branches:
        # Specifies which branches will trigger dependent steps
        include: main

pipelines:
  - name: find_usage
    steps:
      - name: locate_logs
        type: Bash
        configuration:
          environmentVariables:
            path_for_logs:
              default: internal-generic-customer-logs
              description: we will upload customers log under internal-customer-logs and provide path like path_for_logs/jfrog/
              allowCustom: true
          inputResources:
            - name: git_source   # required
        execution:
          onStart:
            - echo "Preparing for work..."
            - echo $path_for_logs
          onExecute:
            - echo $path_for_logs
            - pip install --upgrade pip
            - ls -la
            - cd $res_script_resourcePath
            - ls workspace
            - python start.py
